language: ruby
dist: trusty
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
  - ree
  - rbx-2
  - jruby-9.1.7.0
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
before_install:
  - gem install bundler
